name: dev
variables:
  - name: baseUrl
    value: http://localhost:3000
  - name: roomId
    value: 1c53a7f8-34e6-486f-be31-3c00f27ac3cc
  - name: token
    value: ""
  - name: date
    value: 2026-07-15
  - name: startTime
    value: 09:00
  - name: endTime
    value: 10:00
  - name: reservationId
    value: ""
