name: dev
variables:
  - name: baseUrl
    value: http://localhost:3000
  - name: roomId
    value: 78264b3e-1922-440a-a283-f16c1302f1d9
  - name: token
    value: ''
  - name: date
    value: '2026-07-11'
  - name: startTime
    value: '09:00'
  - name: endTime
    value: '10:00'
  - name: reservationId
    value: ''
